targets:
  ubuntu-16.04:
    build_dependencies:
      - ruby-dev
      - libsqlite3-dev

#  ubuntu-14.04:
  debian-8:
    build_dependencies:
      - ruby-dev
      - libsqlite3-dev
#  debian-7:
#  centos-6:
  centos-7:
    build_dependencies:
      - ruby-devel
    
before:
  - mv ext/pkgr/Gemfile.lock .

cli: jerakia
user: root
group: root
after_install: ext/pkgr/postinstall.sh

env:
  - PACKAGING=1

