targets:
#  ubuntu-16.04:
#  ubuntu-14.04:
#  debian-8:
#  debian-7:
#  centos-6:
  centos-7:
    build_dependencies:
      - ruby-devel
    
cli: jerakia
user: root
group: root
after_install: ext/pkgr/postinstall.sh



